# Generated by Django 4.1.7 on 2023-03-16 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_remove_project_contributor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='project_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='API.project'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='API.project'),
        ),
    ]
